### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by yuanwei0908** [bobo0810/BroadFace#1]
看论文有两个loss,其中L(X)只向embding传输梯度，L(X and E) 只向W传输梯度，感觉应该是两个优化器交替优化，与你的实现似乎不一样，请问对么

**Comment by bobo0810** [comment]
@yuanwei0908 我的理解是：流程是 队列内特征无梯度，mini-batch输出的特征有梯度。两者concat的特征（有梯度）输入分类器。 作者这样画图是更好理解，并非两个Loss。简言之，mini-batch的梯度更新卷积层，mini-batch和队列的concat特征更新分类器。

**Comment by bobo0810** [comment]
@yuanwei0908 readme.md写过，mini-batch和大队列共同作用，产生更好地分类器。更好的分类器才能训练更好的卷积层。同时实验验证效果良好。欢迎探讨，我也仅是片面理解~

**Comment by yuanwei0908** [comment]
@bobo0810 你理解的对，感谢。
