### ISSUE TITLE
Multi-dataset training

### ISSUE THREAD

**Issue by milliema** [bobo0810/BroadFace#2]
Thanks for the code!
请问如果用多个数据集训练，是否要设置多个queue分别存储每个数据集的历史emb和w呢？

**Comment by bobo0810** [comment]
队列用于更新分类器。若有多个分类器（不同分类器 代表 不同数据集的不同类别），则需要多个queue。

**Comment by bobo0810** [comment]
> Thanks for the code!
> 请问如果用多个数据集训练，是否要设置多个queue分别存储每个数据集的历史emb和w呢？

队列用于更新分类器。若有多个分类器（不同分类器 代表 不同数据集的不同类别），则需要多个queue。
